name: Deploy Migrations

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The namespace to deploy to
        required: true
        type: choice
        options:
          - stage1
          - stage2
          - stage3
  workflow_call:
    inputs:
      environment:
        description: The namespace to deploy to
        type: string
        required: true

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    name: Deploy Migrations
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/909613696623/locations/global/workloadIdentityPools/engineering/providers/github"
          service_account: "gcloud-gh-actions@omg-example.iam.gserviceaccount.com"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: GCLOUD
        run: |-
          gcloud secrets versions access "latest" --secret "gh-migration-dsn"
      # - name: Apply all pending migrations to database
      #   run: npx prisma migrate deploy
      #   env:
      #     DSN: ${{ secrets.DSN }}
