name: Deploy Migrations to Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The namespace where migrations will be deployed
        required: true
        type: choice
        options:
          - stage1
          - stage2
          - stage3
      directory:
        description: The repository containing the Prisma migrations
        required: true
        type: string
      branch:
        description: The repository branch
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        description: The namespace where migrations will be deployed
        type: string
        required: true
      directory:
        description: Define directory description here
        type: string
        required: true
      branch:
        description: The repository branch
        type: string
        required: true

jobs:
  get_metadata:
    name: Get Metadata
    runs-on: ubuntu-latest
    outputs:
      secret_name: ${{ steps.get_metadata.outputs.secret_name }}
      env_var_name: ${{ steps.get_metadata.outputs.env_var_name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Metadata
        id: get_metadata
        run: |
          directory=${{ inputs.directory }}
          environment=${{ inputs.environment }}

          FILE_PATH="$directory/metadata-$environment.json"

          # Check if the file exists
          if [ -f "$FILE_PATH" ]; then
            # Extract specific fields from the JSON file and set them as environment variables
            SECRET_NAME=$(jq -r '.secret_name' "$FILE_PATH")
            ENV_VAR_NAME=$(jq -r '.env_var_name' "$FILE_PATH")
            
            echo "secret_name=$SECRET_NAME" >> $GITHUB_OUTPUT
            echo "env_var_name=$ENV_VAR_NAME" >> $GITHUB_OUTPUT
            
          else
            echo "File not found!"
          fi
  deploy:
    name: Deploy
    needs: get_metadata
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write" # Review this permission if needed

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: "orlandorode97/${{ inputs.directory }}"
          ref: ${{ inputs.branch }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/909613696623/locations/global/workloadIdentityPools/engineering/providers/github"
          service_account: "gcloud-gh-actions@omg-example.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Get Secret by Secret Manager
        run: |
          echo "DSN=$(gcloud secrets versions access latest --secret='${{ needs.get_metadata.outputs.secret_name }}')" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.18"

      - name: Installing prisma
        run: npm install prisma

      - name: Apply all pending migrations to database
        run: |
          echo "${{ needs.get_metadata.outputs.env_var_name }}=$DSN"
          npx prisma migrate deploy
          npx prisma --version
