name: Deploy Migrations to Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The namespace where migrations will be deployed
        required: true
        type: choice
        options:
          - stage1
          - stage2
          - stage3
      directory:
        description: The repository containing the Prisma migrations
        required: true
        type: string
      branch:
        description: The repository branch
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        description: The namespace where migrations will be deployed
        type: string
        required: true
      directory:
        description: Define directory description here
        type: string
        required: true
      branch:
        description: The repository branch
        type: string
        required: true

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write" # Review this permission if needed

    name: Deploy Migrations
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify file existence
        run: |
          echo "Listing files in the repository:"
          ls -R # List all files recursively
          echo "Listing files in prisma-gh directory:"
          ls prisma-gh/

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Metadata
        id: get_metadata
        run: |
          directory=${{inputs.directory}}
          environment=${{inputs.environment}}

          FILE_PATH="$directory/metadata-$environment.json"

          # Check if the file exists
          if [ -f "$FILE_PATH" ]; then
            echo "Reading JSON file: $FILE_PATH"
            
            # Extract specific fields from the JSON file and set them as environment variables
            SECRET_NAME=$(jq -r '.secret_name' "$FILE_PATH")
            ENV_VAR_NAME=$(jq -r '.env_var_name' "$FILE_PATH")
            GITHUB_URL=$(jq -r '.github_url' "$FILE_PATH")

            # Set these values as environment variables for use in later steps
            echo "secret_name=$SECRET_NAME" >> $GITHUB_ENV
            echo "env_var_name=$ENV_VAR_NAME" >> $GITHUB_ENV
            echo "github_url=$GITHUB_URL" >> $GITHUB_ENV
            
          else
            echo "File not found!"
          fi

      - name: Use extracted fields
        run: |
          # Access the extracted fields from the previous step using outputs
         echo "Secret Name: ${{ steps.extract_fields.outputs.secret_name }}"
         echo "Environment Variable Name: ${{ steps.extract_fields.outputs.env_var_name }}"
         echo "GitHub URL: ${{ steps.extract_fields.outputs.github_url }}"

      # Uncomment the following steps if necessary

      # - name: Checkout repo "orlandorode97/${{ inputs.repository }}"
      #   uses: actions/checkout@v3
      #   with:
      #     repository: "orlandorode97/${{ inputs.repository }}"
      #     ref: ${{ inputs.branch }}
      #
      # - name: Authenticate to Google Cloud
      #   id: auth
      #   uses: google-github-actions/auth@v2
      #   with:
      #     workload_identity_provider: "projects/909613696623/locations/global/workloadIdentityPools/engineering/providers/github"
      #     service_account: "gcloud-gh-actions@omg-example.iam.gserviceaccount.com"
      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1
      # - name: GCLOUD
      #   run: |-
      #     echo "DSN=$(gcloud secrets
