name: Rollback Migrations in Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The namespace where migrations will be rolled back
        required: true
        type: choice
        options:
          - stage1
          - stage2
          - stage3
      migration_name:
        description: The migration name to execute the rollback e.x `20250324015639_migration_name`
        required: true
        type: string
      repository:
        description: The repository containing the Prisma migrations
        required: true
        type: string
      branch:
        description: The repository branch
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        description: The namespace where migrations will be rolled back
        type: string
        required: true
      repository:
        description: The repository containing the Prisma migrations
        type: string
        required: true
      branch:
        description: The repository branch
        type: string
        required: true

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    name: Rollback Migrations
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repo "orlandorode97/${{ inputs.repository }}"
        uses: actions/checkout@v3
        with:
          repository: "orlandorode97/${{ inputs.repository }}"
          ref: ${{ inputs.branch }}

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/909613696623/locations/global/workloadIdentityPools/engineering/providers/github"
          service_account: "gcloud-gh-actions@omg-example.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: GCLOUD
        run: |-
          echo "DSN=$(gcloud secrets versions access "latest" --secret '${{ inputs.environment }}-migration-dsn')" >> $GITHUB_ENV
      - name: Setting up MySQL env vars
        run: |
          IFS=":/@" read -r _ _ _ MYSQL_USER MYSQL_PWD MYSQL_HOST MYSQL_PORT MYSQL_DB _ <<< "${{ env.DSN }}"

          echo "MYSQL_USER=$MYSQL_USER" >> $GITHUB_ENV
          echo "MYSQL_PWD=$MYSQL_PWD" >> $GITHUB_ENV
          echo "MYSQL_HOST=$MYSQL_HOST" >> $GITHUB_ENV
          echo "MYSQL_PORT=$MYSQL_PORT" >> $GITHUB_ENV
          echo "MYSQL_DB=$MYSQL_DB" >> $GITHUB_ENV

      - name: Execute MySQL query
        env:
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PWD: ${{ env.MYSQL_PWD }}
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
          MYSQL_PORT: ${{ env.MYSQL_PORT }}
          MYSQL_DB: ${{ env.MYSQL_DB }}
        run: |
          FAILED_MIGRATION=$(mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PWD $MYSQL_DB -sN -e "SELECT migration_name FROM `_prisma_migrations` WHERE finished_at IS NULL ORDER BY started_at DESC LIMIT 1")
          echo "FAILED_MIGRATION=$FAILED_MIGRATION" >> $GITHUB_OUTPUT

      - name: Executing rollback migration
        if: steps.deploy.outputs.FAILED_MIGRATION != ''
        run: |-
          npx prisma migrate resolve --rolled-back "${{ steps.deploy.outputs.FAILED_MIGRATION }}"
        env:
          DSN: ${{ env.DSN }}
