name: Generate templated JSON files in new root folders

on:
  push:
    paths:
      - "**/"

permissions:
  contents: write

jobs:
  generate-json-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create missing JSON files
        id: created_metadata_files
        run: |
          REQUIRED_FILES=("metadata-stage1.json" "metadata-stage2.json" "metadata-stage3.json")
          TEMPLATE_FILE="./.template/metadata.json"

          any_changes=false
          for dir in */ ; do
            [[ "$dir" == ".git/" || "$dir" == ".github/" || "$dir" == ".template/" ]] && continue

            for file in "${REQUIRED_FILES[@]}"; do
              if [ ! -f "${dir}${file}" ]; then
                cp "$TEMPLATE_FILE" "${dir}${file}"
                echo "Created ${dir}${file}"
                any_changes=true
              fi
            done
          done

          if [ "$any_changes" = false ]; then
            echo "metadata json files alreay created"
          fi

          echo "any_changes=$any_changes" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: steps.created_metadata_files.outputs.any_changes == 'true'
        run: |
          git config user.name "orlando romo"
          git config user.email "orlando.romo.97@hotmail.com"
          git add .
          git commit -m "Add templated JSON files to new folder" || echo "No changes to commit"
          git push
