name: Rollback failed migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The namespace where migrations will be deployed
        required: true
        type: choice
        options:
          - stage1
          - stage2
          - stage3
      directory:
        description: The repository containing the Prisma migrations
        required: true
        type: string

  workflow_call:
    inputs:
      environment:
        description: The namespace where migrations will be deployed
        type: string
        required: true
      directory:
        description: Define directory description here
        type: string
        required: true

permissions:
  contents: write

jobs:
  get_metadata:
    name: Get Metadata
    runs-on: ubuntu-latest
    outputs:
      secret_name: ${{ steps.get_metadata.outputs.secret_name }}
      env_var_name: ${{ steps.get_metadata.outputs.env_var_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Metadata
        id: get_metadata
        run: |
          directory=${{ inputs.directory }}
          environment=${{ inputs.environment }}

          FILE_PATH="$directory/metadata-$environment.json"

          if [ -f "$FILE_PATH" ]; then
            SECRET_NAME=$(jq -r '.secret_name' "$FILE_PATH")
            ENV_VAR_NAME=$(jq -r '.env_var_name' "$FILE_PATH")

            echo "secret_name=$SECRET_NAME" >> $GITHUB_OUTPUT
            echo "env_var_name=$ENV_VAR_NAME" >> $GITHUB_OUTPUT
          else
            echo "File not found!"
          fi

  setup:
    name: Set up environment
    runs-on: ubuntu-latest
    needs: get_metadata
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/909613696623/locations/global/workloadIdentityPools/engineering/providers/github"
          service_account: "gcloud-gh-actions@omg-example.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Get Secret by Secret Manager
        run: |
          echo "DSN=$(gcloud secrets versions access latest --secret='${{ needs.get_metadata.outputs.secret_name }}')" >> $GITHUB_ENV

      - name: Extract MySQL Credentials and create .my.cnf
        run: |
          IFS=':/@' read -r _ _ _ MYSQL_USER MYSQL_PWD MYSQL_HOST MYSQL_PORT MYSQL_DB _ <<< "${{ env.DSN }}"

          echo "Parsed values:"
          echo "User: $MYSQL_USER"
          echo "Password: $MYSQL_PWD"
          echo "Host: $MYSQL_HOST"
          echo "Port: $MYSQL_PORT"
          echo "Database: $MYSQL_DB"

          cat > .my.cnf << EOF
          [client]
          user=${MYSQL_USER}
          password=${MYSQL_PWD}
          host=${MYSQL_HOST}
          port=${MYSQL_PORT}
          database=${MYSQL_DB}
          EOF

          chmod 600 .my.cnf

      - name: Cat .my.cnf
        run: cat .my.cnf

      - name: Use MySQL with .my.cnf
        run: |
          mysql --defaults-file=.my.cnf -e "SHOW DATABASES;"
